version: '3'

services:
  # [ conatiners ]
  nginx:
    # [ section ]
    build: requirements/nginx
      # [ attribute ]
      # dockerfile:
  # wordpress:
  #   build: requirements/wordpress
  # mariadb:
  #   build: requirements/mariaDB



