#
#---------------------------------------------------------------------------#
#
# # docker compose /`> yml file
#
#----------------------------------------------------------------------#
#

services:

  nginx:
    image: nginx:wp
    container_name: nginx
    restart: on-failure
    build:
      context: $services_path/nginx
      dockerfile: Dockerfile
      labels:
        - app.images.lab=inception
        - lab=inception
    labels:
      - app.containers.lab=inception
    env_file: .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp-db:/var/www/wordpress
    networks:
      - inc@net

  mariadb:
    image: mariadb:wp
    container_name: mariadb
    restart: on-failure
    build:
      context: $services_path/mariaDB
      labels:
        - app.images.lab=inception
        - lab=inception
    labels:
      - app.containers.lab=inception
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inc@net

  wordpress:
    image: wordpress:item
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: on-failure
    build:
      context: $services_path/wordpress
      labels:
        - app.images.lab=inception
        - lab=inception
    labels:
      - app.containers.lab=inception
    volumes:
      - wp-db:/var/www/wordpress
    networks:
      - inc@net

volumes:
  #  WordPress database
  wp-db:
    name: wp-db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
    labels:
      - app.volumes.lab=inception
      - lab=inception
  # WordPress website
  db:
    name: ws-db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
    labels:
      - app.volumes.lab=inception
      - lab=inception

networks:
  inc@net:
    name: inc@net
    labels:
      - app.networks.lab=inception
      - lab=inception
