#
  #___________________________________________________________________________#
  #
  # # docker compose /`> yml file
  #---------------------------------------------------------------------------#

version: '3.8'

services:
  nginx:
    container_name: cn_nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - /var/www:/var/www/
    restart: always
    networks:
      - ince


networks:
  ince:
    driver: bridge