#
  #---------------------------------------------------------------------------#
   #
    # # docker compose /`> yml file
   #
  #----------------------------------------------------------------------#
#
version: '3.8'

services:

  nginx:
    image: nginx:wp
    container_name: nginx
    restart: on-failure
    build:
      context: $services_path/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp-db:/var/www/wordpress
    networks:
      - inc@net

  mariadb:
    image: mariadb:wp
    container_name: mariadb
    restart: on-failure
    build: $services_path/mariaDB
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inc@net

  wordpress:
    image: wordpress:item
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: on-failure
    build: $services_path/wordpress
    volumes:
      - wp-db:/var/www/wordpress
    networks:
      - inc@net

volumes:
  #  WordPress database
  wp-db:
    name: wp-db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tmp/data/mariadb
  # WordPress website
  db:
    name: ws-db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tmp/data/wordpress

networks:
  inc@net:
    name: inc@net
