#========================================================#
# Docker image building that contains last stable debian 
#======================================================#

# deb-OS as
#   base floor
FROM debian:buster

RUN	apt update &&\
    apt upgrade
