#========================================================#
# Docker image building that contains last stable debian 
#======================================================#

# deb-OS as
#   base floor
FROM debian:bullseye

RUN	apt update &&\
    apt upgrade --yes
